# Generated by Django 5.0.7 on 2024-07-21 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(0|0098|\\+98)9(0[1-5]|[1 3]\\d|2[0-2]|9[0-4]|98)\\d{7}$', 'شماره وارد شده مناسب نمی\u200cباشد')]),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Simple', 'Simple')], default='Simple', max_length=10),
        ),
    ]
