# Generated by Django 5.0.7 on 2024-07-27 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'فعال'), ('Paid', 'پرداخت شده'), ('Expired', 'منقضی شده'), ('Failed', 'پرداخت ناموفق')], max_length=20)),
                ('authority', models.CharField(blank=True, max_length=36)),
                ('msg_id', models.CharField(blank=True, max_length=25, null=True)),
                ('telegram_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramprofile', verbose_name='Telegram Account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاکتور های فروش',
                'verbose_name_plural': 'فاکتور های فروش',
            },
        ),
    ]
