# Generated by Django 5.0.7 on 2024-07-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_content_blogpost_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blog.blogpost'),
        ),
    ]
