# Generated by Django 5.0.7 on 2024-07-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcomments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner',
            field=models.ImageField(default='', upload_to='blog/postBanner/'),
            preserve_default=False,
        ),
    ]
