# Generated by Django 5.0.7 on 2024-07-28 11:54

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'تصاویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='postvideos',
            options={'verbose_name': 'فایل ها', 'verbose_name_plural': 'فایل ها'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='banner',
            field=models.ImageField(upload_to='blog/postBanner/', verbose_name='بنر پست'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='caption',
            field=models.CharField(max_length=5000, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='پست ویژه'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='انتشار در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='منتشر شده در'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(max_length=500, null=True, validators=[blog.models.validate_tags], verbose_name="تگ (با '_' جدا می شوند)"),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to='blog/PostContent/video/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='postvideos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.blogpost', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='postvideos',
            name='video',
            field=models.FileField(upload_to='blog/PostContent/video/', verbose_name='فایل'),
        ),
    ]
