# Generated by Django 5.0.7 on 2024-07-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'تنظیمات بات',
                'verbose_name_plural': 'تنظیمات بات',
            },
        ),
        migrations.CreateModel(
            name='SupportAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Telegram', 'تلگرام'), ('Gmail', 'ایمیل'), ('Phone', 'تلفن')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'حساب های پشتیبانی',
                'verbose_name_plural': 'حساب های پشتیبانی',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Forex', 'سیگنال فارکس'), ('Crypto', 'سیگنال کریپتو'), ('TraderBot', 'ربات های تریدر'), ('Broker', 'ثبت نام بروکر'), ('Bonus', 'بونوس'), ('PotentialCurrencies', 'ارزهای پر پتانسیل'), ('Airdrop', 'ایردراپ ها'), ('Eduction', 'آموزش')], max_length=25)),
                ('link', models.CharField(max_length=555)),
            ],
            options={
                'verbose_name': 'لینک های ربات',
                'verbose_name_plural': 'لینک های ربات',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_link', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('access_level', models.CharField(choices=[('Allowed', 'Allowed'), ('Unallowable', 'Unallowable')], max_length=20)),
            ],
            options={
                'verbose_name': 'کابران',
                'verbose_name_plural': 'کابران',
            },
        ),
        migrations.CreateModel(
            name='VipAccountAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expired', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'اشتراک ویژه',
                'verbose_name_plural': 'اشتراک ویژه',
            },
        ),
        migrations.CreateModel(
            name='TelegramTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('text', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], default='Open', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramprofile')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت',
            },
        ),
        migrations.CreateModel(
            name='TelegramTicketAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramticket')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ تیکت',
            },
        ),
    ]
